SPEC = Gem::Specification.new do |spec| 
  spec.name = "bcms_polly"
  spec.rubyforge_project = spec.name
  spec.version = "0.0.1"
  spec.summary = "A Painfully Simple Poll Module for BrowserCMS"
  spec.author = "3months"
  spec.email = "blackadmin@3months.com"
  spec.homepage = "http://3months.com"
  spec.files += Dir["app/**/*"]
  spec.files += Dir["db/migrate/*.rb"]
  spec.files -= Dir["db/migrate/*_browsercms_*.rb"]
  spec.files -= Dir["db/migrate/*_load_seed_data.rb"]
  spec.files += Dir["lib/bcms_polly.rb"]
  spec.files += Dir["lib/bcms_polly/*"]
  spec.files += Dir["rails/init.rb"]
  spec.files += Dir["public/bcms/polly/**/*"]
  spec.has_rdoc = true
  spec.extra_rdoc_files = ["README"]
end
